spring:
  application:
    name: OUTLET-SERVICE
  datasource:
    url : jdbc:mysql://35.222.69.207:3306/outletDb?createDatabaseIfNotExist=true
    username : springuser
    password : springuserpwd
  jpa :
    hibernate :
      ddl-auto : update
server:
  port: 8088